language: go

sudo: false

go:
    - 1.8.x
    - 1.9.x
    - tip

branches:
    only:
        - master

matrix:
    allow_failures:
        - go: tip

before_install:
    - mkdir -p $HOME/bin
    - curl -sL http://get.binhq.io/gitbin | DEST=$HOME/bin bash
    - gitbin get Masterminds/glide 0.13.0 -o $HOME/bin

install: glide install

script: go test $(go list ./... | grep -v /vendor/)
