// Code generated by mockery v1.0.0. DO NOT EDIT.
package correlationid_test

import http "net/http"
import mock "github.com/stretchr/testify/mock"

// correlationIdStore is an autogenerated mock type for the correlationIdStore type
type correlationIdStore struct {
	mock.Mock
}

// StoreCorrelationID provides a mock function with given fields: r, cid
func (_m *correlationIdStore) StoreCorrelationID(r *http.Request, cid string) {
	_m.Called(r, cid)
}
