// Code generated by mockery v1.0.0. DO NOT EDIT.
package correlationid_test

import http "net/http"
import mock "github.com/stretchr/testify/mock"

// correlationIdSource is an autogenerated mock type for the correlationIdSource type
type correlationIdSource struct {
	mock.Mock
}

// ExtractCorrelationID provides a mock function with given fields: r
func (_m *correlationIdSource) ExtractCorrelationID(r *http.Request) string {
	ret := _m.Called(r)

	var r0 string
	if rf, ok := ret.Get(0).(func(*http.Request) string); ok {
		r0 = rf(r)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
