// Code generated by mockery v1.0.0. DO NOT EDIT.
package correlationid_test

import context "context"

import mock "github.com/stretchr/testify/mock"

// correlationIdStore is an autogenerated mock type for the correlationIdStore type
type correlationIdStore struct {
	mock.Mock
}

// StoreCorrelationID provides a mock function with given fields: ctx, cid
func (_m *correlationIdStore) StoreCorrelationID(ctx context.Context, cid string) {
	_m.Called(ctx, cid)
}
