// Code generated by mockery v1.0.0. DO NOT EDIT.
package tagscorrelationid_test

import context "context"

import mock "github.com/stretchr/testify/mock"

// correlationIdSource is an autogenerated mock type for the correlationIdSource type
type correlationIdSource struct {
	mock.Mock
}

// ExtractCorrelationID provides a mock function with given fields: ctx
func (_m *correlationIdSource) ExtractCorrelationID(ctx context.Context) string {
	ret := _m.Called(ctx)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
